### ISSUE TITLE
default to find gamma in Variables

### ISSUE THREAD

**Issue by jepetolee** [MarkusAI/rA9#17]
![image](https://user-images.githubusercontent.com/55366212/95774810-18112200-0cfc-11eb-8ed8-b7209b00df4d.png)

I think you didn't commit your latest backend, so if you read this Issue, give me changed backend codes to usb.

**Comment by Dongyeongkim** [comment]
No, actually that is right. I did it by changing the return value that np_args is equal as np_grad_args

**Comment by Dongyeongkim** [comment]
Ah, I was misunderstood. I added. This Issue is done
