### ISSUE TITLE
The poisson Encoder might be wrecked by me LOL

### ISSUE THREAD

**Issue by Dongyeongkim** [MarkusAI/rA9#59]
The design of Poison encoder is wrecked i think.

**Comment by Dongyeongkim** [comment]
Need to make PoissonEncoder as DataLoading Option..

**Comment by Dongyeongkim** [comment]
Need comments @jepetolee

**Comment by jepetolee** [comment]
ok

**Comment by Dongyeongkim** [comment]
not wrecked has been confirmed
