### ISSUE TITLE
graident didn't work

### ISSUE THREAD

**Issue by Dongyeongkim** [MarkusAI/rA9#95]
It didn't work

**Comment by Dongyeongkim** [comment]
The problem is when we try to use grad for optimizing weights, it has different.
for grad to get another grad-> just through it
for grad to optimize -> it is quite different. need to get delta W for it. delta W is equal as deltaE*Xl(t)/deltaW*grad

**Comment by Dongyeongkim** [comment]
![image](https://user-images.githubusercontent.com/42883224/101917989-2b614080-3c0c-11eb-9c27-bdd6f1d57028.png)

**Comment by Dongyeongkim** [comment]
Not really overside. real formula is 
![image](https://user-images.githubusercontent.com/42883224/102040223-7f884280-3e0f-11eb-9c96-16f174496d15.png)
so the #96 is wrong implementation. need to make it right.

**Comment by jepetolee** [comment]
LInear layer was well-worked, but after pooling layers, it did'nt works. So, I'll try to fix this error

**Comment by Dongyeongkim** [comment]
there has problem in linear layer too. need to review

**Comment by Dongyeongkim** [comment]
ValueError: Incompatible shapes for broadcasting: (300, 784) and requested shape (64, 784)

might be the problem of transpose

**Comment by Dongyeongkim** [comment]
loss.backward() didn't work due to dimension error

**Comment by Dongyeongkim** [comment]
it is resolved

but need to test gradient

**Comment by Dongyeongkim** [comment]
might be the problem of encoding or somehow?

**Comment by Dongyeongkim** [comment]
It didn't work in fully-connected and Convolution, just swing away in range +- 1.x

**Comment by Dongyeongkim** [comment]
Engine has problem. When you see engine in output, you need to elementwise multifiplying Time range(T in paper) but you matrix multiplicating grad so it went grad square indeed. need to change engine

**Comment by Dongyeongkim** [comment]
#100 detailed-description

**Comment by Dongyeongkim** [comment]
Not really. the real problem is the position of grad and gamma, matrix multiplication has directional factor so @jepetolee and @Dongyeongkim will fix it

**Comment by Dongyeongkim** [comment]
#101 has been tested. and the solution is confirmed. this case is signed a die

**Comment by Dongyeongkim** [comment]
the case which is opened: Convolution and pooling backward

**Comment by Dongyeongkim** [comment]
need to test #102

**Comment by Dongyeongkim** [comment]
mini-Batch algorithm need to be understood, it is likely to get an average of error gradient

**Comment by Dongyeongkim** [comment]
Well the states of neurons which is based on batch data is different.

ex) 1,2,3 -> have different membrane potentials because data is different

grad is not equal, weight is equal, LIF' is equal. 

so the grad has different in regard to an element of batch.

**Comment by Dongyeongkim** [comment]
need test but not now
